apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tf-gpu-test-job
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tf-gpu-test-job
            image: tf-gpu-test-job:latest
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: tf-gpu-test-job-creds
              - configMapRef:
                  name: tf-gpu-test-job-config
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '0 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false

